<?php
session_start();
if (!isset($_SESSION['user'])) { header('Location: login.php'); exit; }
$orders = json_decode(file_get_contents('../data/order.json'), true);
$user_orders = array_filter($orders, fn($o) => $o['customer_email'] === $_SESSION['user']['email']);
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Order History — King's Cup</title><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"></head>
<body>
<nav class="navbar"><div class="nav-inner"><a href="index.php" class="nav-logo"><div class="logo-icon"><svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="18" fill="#3b1f0e"/><path d="M10 22 Q12 14 18 12 Q24 14 26 22 Q22 26 18 27 Q14 26 10 22Z" fill="#c8860a"/><circle cx="18" cy="19" r="4" fill="#3b1f0e"/></svg></div><span class="logo-text">King's Cup</span></a><ul class="nav-links"><li><a href="menu.php">Menu</a></li><li><a href="view_orders.php">View Orders</a></li><li><a href="order_status.php">Order Status</a></li><li><a href="order_history.php" class="active">Order History</a></li></ul><a href="profile.php" class="nav-profile"><svg width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="#c8860a"/><circle cx="16" cy="13" r="5" fill="white"/><path d="M6 26c0-5.523 4.477-8 10-8s10 2.477 10 8" fill="white"/></svg></a><button class="hamburger" id="hamburger">☰</button></div></nav>
<div class="oh-page"><div class="oh-title-bar"><h1>Your History</h1></div><?php if (empty($user_orders)): ?><div class="vo-empty"><div class="vo-empty-icon">📋</div><h2>No order history yet</h2><p>Place an order and it will appear here.</p><a href="menu.php" class="btn-vo-menu">Browse Menu</a></div><?php else: ?><?php foreach (array_reverse($user_orders) as $order): ?><div class="oh-group"><div class="oh-date">Placed on <?= date('F j, Y', strtotime($order['placed_at'])) ?></div><div class="oh-table-wrap"><table class="vo-table"><thead><tr><th class="th-product">Products Ordered</th><th>Unit Price</th><th>Qty</th><th>Sub Total</th></tr></thead><tbody><?php foreach ($order['items'] as $item): ?><tr><td class="td-product"><img src="<?= htmlspecialchars($item['img']) ?>" alt="<?= htmlspecialchars($item['name']) ?>"><span class="td-name"><?= htmlspecialchars($item['name']) ?></span></td><td>₱<?= number_format($item['price']) ?></td><td><?= $item['quantity'] ?></td><td>₱<?= number_format($item['price'] * $item['quantity']) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><td colspan="2" class="tf-label">Order Total:</td><td class="tf-total">₱<?= number_format($order['total']) ?></td></tr></tfoot></table></div><div class="oh-order-meta"><span class="oh-order-num"><?= htmlspecialchars($order['id']) ?></span><span class="oh-status"><?= htmlspecialchars($order['status']) ?></span></div></div><?php endforeach; ?><?php endif; ?></div>
<footer class="footer"><div class="footer-inner"><div class="footer-contact"><p class="footer-label">Contact us via:</p><p>vibri@gmail.com</p><p>King's Cup Coffee</p></div><div class="footer-copy"><p>&copy; <?= date('Y') ?> King's Cup Coffee Enterprises. All rights reserved.</p></div></div></footer>
<script src="main.js"></script>
</body>
</html>