<?php
session_start();
if (empty($_SESSION['user'])) { header('Location: login.php'); exit; }
if (isset($_GET['logout'])) { session_destroy(); header('Location: login.php'); exit; }
$user = $_SESSION['user'];
$stored = $_SESSION['registered_user'] ?? [];
$orders = json_decode(file_get_contents('../data/order.json'), true);
$user_orders = array_filter($orders, fn($o) => $o['customer_email'] === $user['email']);
$total_spent = array_sum(array_column($user_orders, 'total'));
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Profile — King's Cup</title><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Lato:wght@300;400;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"></head>
<body>
<nav class="navbar"><div class="nav-inner"><a href="index.php" class="nav-logo"><div class="logo-icon"><svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="18" fill="#3b1f0e"/><path d="M10 22 Q12 14 18 12 Q24 14 26 22 Q22 26 18 27 Q14 26 10 22Z" fill="#c8860a"/><circle cx="18" cy="19" r="4" fill="#3b1f0e"/></svg></div><span class="logo-text">King's Cup</span></a><ul class="nav-links"><li><a href="menu.php">Menu</a></li><li><a href="view_orders.php">View Orders</a></li><li><a href="order_status.php">Order Status</a></li><li><a href="order_history.php">Order History</a></li></ul><a href="profile.php" class="nav-profile nav-profile-active"><svg width="32" height="32" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="#c8860a"/><circle cx="16" cy="13" r="5" fill="white"/><path d="M6 26c0-5.523 4.477-8 10-8s10 2.477 10 8" fill="white"/></svg></a><button class="hamburger" id="hamburger">☰</button></div></nav>
<div class="prof-page"><div class="prof-hero"><div class="prof-avatar"><?= strtoupper(substr($user['name'] ?? 'U',0,1)) ?></div><div class="prof-hero-info"><h2><?= htmlspecialchars($user['name'] ?? 'Guest') ?></h2><p class="prof-username">@<?= htmlspecialchars($user['username'] ?? 'user') ?></p><p class="prof-email"><?= htmlspecialchars($user['email'] ?? '') ?></p></div></div><div class="prof-stats"><div class="prof-stat"><span class="prof-stat-value"><?= count($user_orders) ?></span><span class="prof-stat-label">Orders Placed</span></div><div class="prof-stat"><span class="prof-stat-value">₱<?= number_format($total_spent) ?></span><span class="prof-stat-label">Total Spent</span></div><div class="prof-stat"><span class="prof-stat-value">☕</span><span class="prof-stat-label">Coffee Lover</span></div></div><div class="prof-card"><h3 class="prof-card-title">Account Details</h3><div class="prof-detail-row"><span class="prof-detail-label">Full Name</span><span class="prof-detail-value"><?= htmlspecialchars($stored['name'] ?? $user['name'] ?? '—') ?></span></div><div class="prof-detail-row"><span class="prof-detail-label">Username</span><span class="prof-detail-value">@<?= htmlspecialchars($stored['username'] ?? $user['username'] ?? '—') ?></span></div><div class="prof-detail-row"><span class="prof-detail-label">Email</span><span class="prof-detail-value"><?= htmlspecialchars($stored['email'] ?? $user['email'] ?? '—') ?></span></div><?php if (!empty($stored['phone'])): ?><div class="prof-detail-row"><span class="prof-detail-label">Phone</span><span class="prof-detail-value"><?= htmlspecialchars($stored['phone']) ?></span></div><?php endif; ?><?php if (!empty($stored['dob'])): ?><div class="prof-detail-row"><span class="prof-detail-label">Date of Birth</span><span class="prof-detail-value"><?= htmlspecialchars($stored['dob']) ?></span></div><?php endif; ?></div><div class="prof-card"><h3 class="prof-card-title">Quick Links</h3><div class="prof-links"><a href="order_history.php" class="prof-link"><span class="prof-link-icon">📋</span> View Order History</a><a href="order_status.php" class="prof-link"><span class="prof-link-icon">🔄</span> Track Current Order</a><a href="login.php?page=reset-password" class="prof-link"><span class="prof-link-icon">🔑</span> Change Password</a><a href="profile.php?logout=1" class="prof-link prof-link-danger"><span class="prof-link-icon">🚪</span> Log Out</a></div></div></div>
<footer class="footer"><div class="footer-inner"><div class="footer-contact"><p class="footer-label">Contact us via:</p><p>vibri@gmail.com</p><p>King's Cup Coffee</p></div><div class="footer-copy"><p>&copy; <?= date('Y') ?> King's Cup Coffee Enterprises. All rights reserved.</p></div></div></footer>
<script src="main.js"></script>
</body>
</html>